# Generated by Django 3.2.6 on 2021-09-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('BNB', 'BNB')], max_length=10)),
                ('fee', models.FloatField(max_length=5)),
                ('price', models.FloatField(max_length=10)),
                ('amount', models.FloatField(max_length=10)),
            ],
        ),
    ]
