# Generated by Django 3.2.6 on 2021-09-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0006_transaction_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_record',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
