# Generated by Django 3.2.6 on 2021-09-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0007_alter_transaction_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_record',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
