# Generated by Django 3.2.6 on 2021-09-11 04:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0009_alter_transaction_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_record',
            name='buy_or_sell',
            field=models.BooleanField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
