# Generated by Django 3.2.6 on 2021-09-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0010_transaction_record_buy_or_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_record',
            name='buy_or_sell',
            field=models.BooleanField(default=True),
        ),
    ]
