# Generated by Django 3.2.6 on 2021-09-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0013_transaction_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_record',
            name='buy_or_sell',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=5),
        ),
    ]
