# Generated by Django 3.2.7 on 2021-09-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0014_alter_transaction_record_buy_or_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_record',
            name='type',
            field=models.CharField(choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('BNB', 'BNB'), ('VET', 'VET'), ('ADA', 'ADA'), ('LINK', 'LINK'), ('DOGE', 'DOGE'), ('FIL', 'FIL'), ('DOT', 'DOT')], max_length=10),
        ),
    ]
